### ISSUE TITLE
CONTRIBUTING

### ISSUE THREAD

**Issue by jhampton** [justin-coberly/dagre-d3-react#1]
Hello Justin!

I just found this package and I'll be giving it a spin.  Rather than just `fork`ing into my own repo, I checked to see if you have a `CONTRIBUTING.md` to guide those of us who might want to help.

I hope you're well, and thank you for this project!

**Comment by justin-coberly** [comment]
Thank you for reaching our Jeff, any help would be greatly appreciated! A basic contributing.md file has been uploaded.

**Comment by jhampton** [comment]
Awesome, thank you so much Justin!  I’ve got a conference this week, but I’m hoping to integrate it next week.

Thanks again for the project!
