### ISSUE TITLE
Unremoved log

### ISSUE THREAD

**Issue by carlflor** [justin-coberly/dagre-d3-react#11]
https://github.com/justin-coberly/dagre-d3-react/blob/7ab99554b0a2309476bed4d168cc711aadf52c1d/src/index.tsx#L74

Hi! Great work!
I noticed you might have forgotten to remove a log in your code? Or was that placed on purpose?

**Comment by justin-coberly** [comment]
@carlflor  Ha! this was definately not supposed to be in there. Thank you for catching it.

**Comment by carlflor** [comment]
no prob :)
