### ISSUE TITLE
How to remove arrowhead and curve the edges?

### ISSUE THREAD

**Issue by davidudemann** [justin-coberly/dagre-d3-react#7]

**Comment by justin-coberly** [comment]
@davidudemann  my code currently doesn't allow it, but curving the edges can be easily implemented in the dagre library. I will go ahead and make this a feature request and work on integrating it in my spare time.

**Comment by justin-coberly** [comment]
@davidudemann  v0.2.2 is out and should allow you to make those changes. Just add a config property to your links.
```
{
		source: '5',
		target: '8',
		label: 'then',
		config: {
			arrowheadStyle: 'display: none', //hides arrowhead
			curve: d3.curveBasis //creates curved lines
		}
	}
```
